import regex
import statistics
import os
import sys
from processVariables import walkObjects

if len(sys.argv) <= 1:
    print("usage: ./addSerialization.py object-directory")
    sys.exit()
    
eventMarker = "<event eventtype=\"{}\" enumb=\"{}\">"
reEventMarker = regex.compile(eventMarker.format("([0-9]+)", "([0-9]+)"))
reAutoGenerateTag = regex.compile(r"/[/\*][/\*\s]*@autogenerate", regex.IGNORECASE)

newEvent = \
"""{}<event eventtype="7" enumb="15">
      <action>
        <libid>1</libid>
        <id>603</id>
        <kind>7</kind>
        <userelative>0</userelative>
        <isquestion>0</isquestion>
        <useapplyto>-1</useapplyto>
        <exetype>2</exetype>
        <functionname></functionname>
        <codestring></codestring>
        <whoName>self</whoName>
        <relative>0</relative>
        <isnot>0</isnot>
        <arguments>
          <argument>
            <kind>1</kind>
            <string>{}</string>
          </argument>
        </arguments>
      </action>
    </event>
"""

for result in walkObjects("../objects", True):
    fcontents = ""
    with open(result.path, "r", encoding="utf8") as file:
        fcontents = file.read()
    
    ev5Index = fcontents.find(eventMarker.format("7", "15"))
    ev5Span = ()
    addEventsTag = "    "
    if ev5Index == -1:
        # insert after previous event
        prevIndex = -1
        while True:
            match = reEventMarker.search(fcontents, prevIndex + 1)
            if match is None:
                break
            index = match.span()[0]
            if int(match.group(1)) > 7:
                break
            elif int(match.group(1)) == 7 and int(match.group(2)) > 15:
                break
            prevIndex = index
        # find suitable insertion for end of previous event:
        if prevIndex == -1:
            # no events prior to insertion point.
            ev5Index = fcontents.find("<events>") + len("<events>\n")
            if ev5Index == -1:
                # no events at all!
                ev5Index = fcontents.find("<events/>")
                assert(ev5Index != -1)
                addEventsTag="  <events>\n    "
            ev5Span = (ev5Index, ev5Index)
        else:
            # an insertion point was found.
            ev5Index = fcontents.find("</event>", prevIndex) + len("</event>\n")
            ev5Span = (ev5Index, ev5Index)
    else:
        # replace existing user-event 5
        ev5EndIndex = fcontents.find("</event>", ev5Index)
        if ev5EndIndex == -1:
            # broken
            continue
        else:
            ev5Span = (ev5Index, ev5EndIndex + len("</event>"))
            addEventsTag = ""
            if reAutoGenerateTag.search(fcontents, ev5Index, ev5EndIndex) is None:
                # file marked as non-autogenerable
                continue

    # now have ev5Span, substitute in code.

    # determine code:
    code = \
"""/// Serialize instance variables.
/// This code was autogenerated by addSerialization.py

// Before editing manually, remove the following tag so that
// this event is not replaced when autogenerated again.

// @autogenerate

"""
    hasSerialization = False
    hasVars = False
    if result.parentResult is None:
        code += "// This object has no parent, so it is responsible\n// for encoding basic instance properties.\n"
        code += "stateCodecInstance();\n\n"
        hasSerialization = True
    else:
        code += "event_inherited();\n\n"
    codeEncode = "\n"
    codeDecode = "\n"
    indent = "    "
    for var in result.instanceVariablesDefinite:
        hasSerialization = True
        hasVars = True
        if var in sorted(list(result.instanceVariableType.keys())):
            swizzledType = result.instanceVariableType[var]
            if swizzledType == 'id':
                codeEncode += "{}stateCodecIDEncode({});\n".format(indent, var)
                codeDecode += "{}{} = stateCodecIDDecode();\n".format(indent, var)
            else:
                # encoding/decoding data structures will require a lot of sneakiness.
                codeEncode += "{}stateCodecDSEncode({}, ds_type_{});\n".format(indent, var, swizzledType)
                codeDecode += "{}{} = stateCodecDSDecode(ds_type_{});\n".format(indent, var, swizzledType)
        else:
            codeEncode += "{}stateCodecPrimitiveEncode({});\n".format(indent, var)
            codeDecode += "{}{} = stateCodecPrimitiveDecode();\n".format(indent, var)
            

    if hasSerialization:
        if hasVars:
            code += "if (global.stateCodecEncode)\n{{{}}}\nelse\n{{{}}}\n"
        code = code.format(codeEncode, codeDecode)
        fcontents = fcontents[:ev5Span[0]] + newEvent.format(addEventsTag, code) + fcontents[ev5Span[1]:]
        with open(result.path, "w", encoding="utf8") as file:
            file.write(fcontents)
