/// encodes/decodes global variables.

if (global.stateCodecEncode)
{
    stateCodecPrimitiveEncode(view_xview[0])
    stateCodecPrimitiveEncode(view_yview[0])
    stateCodecPrimitiveEncode(global.aliveBosses)
    stateCodecPrimitiveEncode(global.alwaysHealth)
    stateCodecPrimitiveEncode(global.ammo)
    stateCodecPrimitiveEncode(global.beginHubOnRoomBegin)
    stateCodecPrimitiveEncode(global.beginStageOnRoomBegin)
    stateCodecPrimitiveEncode(global.bolts)
    stateCodecDSEncode(global.borderlist, ds_type_map)
    stateCodecPrimitiveEncode(global.borderLockBottom)
    stateCodecPrimitiveEncode(global.borderLockLeft)
    stateCodecPrimitiveEncode(global.borderLockRight)
    stateCodecPrimitiveEncode(global.borderLockTop)
    stateCodecPrimitiveEncode(global.bossTextShown)
    stateCodecPrimitiveEncode(global.BounceXVel)
    stateCodecPrimitiveEncode(global.cachedXView)
    stateCodecPrimitiveEncode(global.cachedYView)
    stateCodecPrimitiveEncode(global.castleStagesBeaten)
    stateCodecPrimitiveEncode(global.characterSelected)
    stateCodecPrimitiveEncode(global.chargeUpgrade)
    stateCodecPrimitiveEncode(global.checkpoint)
    stateCodecPrimitiveEncode(global.checkpointNotification)
    stateCodecPrimitiveEncode(global.checkpointX)
    stateCodecPrimitiveEncode(global.checkpointY)
    stateCodecPrimitiveEncode(global.converter)
    stateCodecPrimitiveEncode(global.coop)
    stateCodecPrimitiveEncode(global.costumeRequirement)
    stateCodecPrimitiveEncode(global.createArgument)
    stateCodecPrimitiveEncode(global.deathEffect)
    stateCodecPrimitiveEncode(global.debugSkipStageMode)
    stateCodecPrimitiveEncode(global.decrementLivesOnRoomEnd)
    stateCodecPrimitiveEncode(global.defaultLives)
    stateCodecPrimitiveEncode(global.difficulty)
    stateCodecPrimitiveEncode(global.disableChargeUpgrade)
    stateCodecPrimitiveEncode(global.disableConverter)
    stateCodecPrimitiveEncode(global.disableDropUpgrade)
    stateCodecPrimitiveEncode(global.disableShotUpgrade)
    stateCodecPrimitiveEncode(global.disableSkullAmulet)
    stateCodecPrimitiveEncode(global.disableSturdyHelmet)
    stateCodecPrimitiveEncode(global.dropUpgrade)
    stateCodecPrimitiveEncode(global.eddieisdead)
    stateCodecPrimitiveEncode(global.elementsCollected)
    stateCodecPrimitiveEncode(global.enableCharge)
    stateCodecPrimitiveEncode(global.enableSlide)
    stateCodecPrimitiveEncode(global.endStageOnRoomEnd)
    stateCodecPrimitiveEncode(global.energyElements)
    stateCodecPrimitiveEncode(global.energySaver)
    stateCodecPrimitiveEncode(global.eTanks)
    stateCodecPrimitiveEncode(global.eventArgs)
    stateCodecPrimitiveEncode(global.execute_gml_function_ERR)
    stateCodecPrimitiveEncode(global.factionStance)
    stateCodecPrimitiveEncode(global.familyFriendlyText)
    stateCodecPrimitiveEncode(global.flag)
    stateCodecPrimitiveEncode(global.flagParent)
    stateCodecPrimitiveEncode(global.flashTimer)
    stateCodecPrimitiveEncode(global.font)
    stateCodecPrimitiveEncode(global.freeMovement)
    stateCodecPrimitiveEncode(global.frozen)
    stateCodecPrimitiveEncode(global.gameSpeed)
    stateCodecPrimitiveEncode(global.gameTimer)
    stateCodecPrimitiveEncode(global.gml_fn_retval)
    stateCodecDSEncode(global.gravityLiftBulletMap, ds_type_map)
    stateCodecDSEncode(global.gravityLiftLockJumpMap, ds_type_map)
    stateCodecDSEncode(global.gravityLiftLockMap, ds_type_map)
    stateCodecDSEncode(global.gravityLiftXSpeedMap, ds_type_map)
    stateCodecPrimitiveEncode(global.gunshot)
    stateCodecPrimitiveEncode(global.hasTeleported)
    stateCodecPrimitiveEncode(global.healthEffect)
    stateCodecPrimitiveEncode(global.infiniteEnergy)
    stateCodecPrimitiveEncode(global.inGame)
    stateCodecPrimitiveEncode(global.isInvincible)
    stateCodecPrimitiveEncode(global.jumpSound)
    stateCodecPrimitiveEncode(global.keyCoinCollected)
    stateCodecPrimitiveEncode(global.keyCoinTotal)
    stateCodecPrimitiveEncode(global.keyNumber)
    stateCodecPrimitiveEncode(global.lastTeleporterX)
    stateCodecPrimitiveEncode(global.lastTeleporterY)
    stateCodecPrimitiveEncode(global.levelLoop)
    stateCodecPrimitiveEncode(global.levelLoopEnd)
    stateCodecPrimitiveEncode(global.levelLoopStart)
    stateCodecPrimitiveEncode(global.levelReward)
    stateCodecPrimitiveEncode(global.levelRunInvalidReason)
    stateCodecPrimitiveEncode(global.levelRunValid)
    stateCodecPrimitiveEncode(global.levelSong)
    stateCodecPrimitiveEncode(global.levelSongType)
    stateCodecPrimitiveEncode(global.levelTrackNumber)
    stateCodecPrimitiveEncode(global.levelVolume)
    stateCodecPrimitiveEncode(global.leverPropagated)
    stateCodecPrimitiveEncode(global.livesEnabled)
    stateCodecPrimitiveEncode(global.livesRemaining)
    stateCodecPrimitiveEncode(global.lockBuster)
    stateCodecPrimitiveEncode(global.lockPoolAvailable)
    stateCodecPrimitiveEncode(global.lockPoolLockCount)
    stateCodecPrimitiveEncode(global.lockPoolLockTable)
    stateCodecPrimitiveEncode(global.lockPoolN)
    stateCodecPrimitiveEncode(global.lockPoolTombstone)
    stateCodecPrimitiveEncode(global.lockTransition)
    stateCodecPrimitiveEncode(global.maxBolts)
    stateCodecPrimitiveEncode(global.maxETanks)
    stateCodecPrimitiveEncode(global.maxLives)
    stateCodecPrimitiveEncode(global.maxMTanks)
    stateCodecPrimitiveEncode(global.maxPlayerCount)
    stateCodecPrimitiveEncode(global.maxWTanks)
    stateCodecPrimitiveEncode(global.MeBounce)
    stateCodecPrimitiveEncode(global.mmColor)
    stateCodecPrimitiveEncode(global.mTanks)
    stateCodecPrimitiveEncode(global.musicsound)
    stateCodecPrimitiveEncode(global.nextRoom)
    stateCodecPrimitiveEncode(global.outlineCol)
    stateCodecPrimitiveEncode(global.pickupGraphics)
    stateCodecPrimitiveEncode(global.playerCount)
    stateCodecPrimitiveEncode(global.playerCountInitialized)
    stateCodecPrimitiveEncode(global.playerFrozen)
    stateCodecPrimitiveEncode(global.playerHealth)
    stateCodecPrimitiveEncode(global.playerLock)
    stateCodecPrimitiveEncode(global.playerProjectileCreator)
    stateCodecPrimitiveEncode(global.playerSprite)
    stateCodecPrimitiveEncode(global.playerSpriteMax)
    stateCodecPrimitiveEncode(global.playingcustommusic)
    stateCodecPrimitiveEncode(global.previousRoom)
    stateCodecPrimitiveEncode(global.prevXView)
    stateCodecPrimitiveEncode(global.prevYView)
    stateCodecPrimitiveEncode(global.primaryCol)
    stateCodecPrimitiveEncode(global.quadHeight)
    stateCodecPrimitiveEncode(global.quadMarginBottom)
    stateCodecPrimitiveEncode(global.quadMarginTop)
    stateCodecPrimitiveEncode(global.quadWidth)
    stateCodecPrimitiveEncode(global.queuePaused)
    stateCodecPrimitiveEncode(global.respawnAllowed)
    stateCodecPrimitiveEncode(global.respawnAnimation)
    stateCodecPrimitiveEncode(global.respawnDonateThreshold)
    stateCodecPrimitiveEncode(global.respawnGravityAngle)
    stateCodecPrimitiveEncode(global.respawnTime)
    stateCodecPrimitiveEncode(global.respawnTimeBoss)
    stateCodecPrimitiveEncode(global.respawnTimer)
    stateCodecPrimitiveEncode(global.retval)
    stateCodecPrimitiveEncode(global.retval_error)
    stateCodecPrimitiveEncode(global.retval_exprlen)
    stateCodecPrimitiveEncode(global.retval_exprval)
    stateCodecPrimitiveEncode(global.roomReturn)
    stateCodecPrimitiveEncode(global.roomReturnIsHub)
    stateCodecPrimitiveEncode(global.roomReturnIsStage)
    stateCodecPrimitiveEncode(global.roomTimer)
    stateCodecPrimitiveEncode(global.secondaryCol)
    stateCodecPrimitiveEncode(global.sectionBottom)
    stateCodecPrimitiveEncode(global.sectionLeft)
    stateCodecPrimitiveEncode(global.sectionRight)
    stateCodecPrimitiveEncode(global.sectionTop)
    stateCodecPrimitiveEncode(global.shakeFactorX)
    stateCodecPrimitiveEncode(global.shakeFactorY)
    stateCodecPrimitiveEncode(global.shakeTimer)
    stateCodecPrimitiveEncode(global.sheepBlockStack)
    stateCodecPrimitiveEncode(global.sheepBlockStack_n)
    stateCodecPrimitiveEncode(global.shotUpgrade)
    stateCodecPrimitiveEncode(global.showMovingText)
    stateCodecPrimitiveEncode(global.skullAmulet)
    stateCodecPrimitiveEncode(global.songMemory)
    stateCodecPrimitiveEncode(global.soundvolume)
    stateCodecPrimitiveEncode(global.stageStartRoom)
    stateCodecPrimitiveEncode(global.sturdyHelmet)
    stateCodecPrimitiveEncode(global.superArmInterface)
    stateCodecPrimitiveEncode(global.switchingSections)
    stateCodecPrimitiveEncode(global.teleportSound)
    stateCodecPrimitiveEncode(global.teleportX)
    stateCodecPrimitiveEncode(global.teleportY)
    stateCodecPrimitiveEncode(global.telTelWeather)
    stateCodecPrimitiveEncode(global.tempSongData)
    stateCodecPrimitiveEncode(global.tileLayers)
    stateCodecPrimitiveEncode(global.tileLayersN)
    stateCodecPrimitiveEncode(global.timeStopped)
    stateCodecPrimitiveEncode(global.totalWeapons)
    stateCodecPrimitiveEncode(global.vsync)
    stateCodecPrimitiveEncode(global.waveManWarpLock)
    stateCodecPrimitiveEncode(global.weapon)
    stateCodecPrimitiveEncode(global.weaponHotbar)
    stateCodecPrimitiveEncode(global.weaponIcon)
    stateCodecPrimitiveEncode(global.weaponLocked)
    stateCodecPrimitiveEncode(global.weaponName)
    stateCodecPrimitiveEncode(global.weaponObject)
    stateCodecPrimitiveEncode(global.weaponPrimaryColor)
    stateCodecPrimitiveEncode(global.weaponSecondaryColor)
    stateCodecPrimitiveEncode(global.wTanks)
    stateCodecPrimitiveEncode(global.keyLeft);
    stateCodecPrimitiveEncode(global.keyRight);
    stateCodecPrimitiveEncode(global.keyUp);
    stateCodecPrimitiveEncode(global.keyDown);
    stateCodecPrimitiveEncode(global.keyJump);
    stateCodecPrimitiveEncode(global.keyShoot);
    stateCodecPrimitiveEncode(global.keySlide);
    stateCodecPrimitiveEncode(global.keyPause);
    stateCodecPrimitiveEncode(global.keyWeaponSwitchLeft);
    stateCodecPrimitiveEncode(global.keyWeaponSwitchRight);
}
else
{
    global.view_xview[0] = stateCodecPrimitiveDecode()
    global.view_yview[0] = stateCodecPrimitiveDecode()
    global.aliveBosses = stateCodecPrimitiveDecode()
    global.alwaysHealth = stateCodecPrimitiveDecode()
    global.ammo = stateCodecPrimitiveDecode()
    global.beginHubOnRoomBegin = stateCodecPrimitiveDecode()
    global.beginStageOnRoomBegin = stateCodecPrimitiveDecode()
    global.bolts = stateCodecPrimitiveDecode()
    global.borderlist = stateCodecDSDecode(ds_type_map)
    global.borderLockBottom = stateCodecPrimitiveDecode()
    global.borderLockLeft = stateCodecPrimitiveDecode()
    global.borderLockRight = stateCodecPrimitiveDecode()
    global.borderLockTop = stateCodecPrimitiveDecode()
    global.bossTextShown = stateCodecPrimitiveDecode()
    global.BounceXVel = stateCodecPrimitiveDecode()
    global.cachedXView = stateCodecPrimitiveDecode()
    global.cachedYView = stateCodecPrimitiveDecode()
    global.castleStagesBeaten = stateCodecPrimitiveDecode()
    global.characterSelected = stateCodecPrimitiveDecode()
    global.chargeUpgrade = stateCodecPrimitiveDecode()
    global.checkpoint = stateCodecPrimitiveDecode()
    global.checkpointNotification = stateCodecPrimitiveDecode()
    global.checkpointX = stateCodecPrimitiveDecode()
    global.checkpointY = stateCodecPrimitiveDecode()
    global.converter = stateCodecPrimitiveDecode()
    global.coop = stateCodecPrimitiveDecode()
    global.costumeRequirement = stateCodecPrimitiveDecode()
    global.createArgument = stateCodecPrimitiveDecode()
    global.deathEffect = stateCodecPrimitiveDecode()
    global.debugSkipStageMode = stateCodecPrimitiveDecode()
    global.decrementLivesOnRoomEnd = stateCodecPrimitiveDecode()
    global.defaultLives = stateCodecPrimitiveDecode()
    global.difficulty = stateCodecPrimitiveDecode()
    global.disableChargeUpgrade = stateCodecPrimitiveDecode()
    global.disableConverter = stateCodecPrimitiveDecode()
    global.disableDropUpgrade = stateCodecPrimitiveDecode()
    global.disableShotUpgrade = stateCodecPrimitiveDecode()
    global.disableSkullAmulet = stateCodecPrimitiveDecode()
    global.disableSturdyHelmet = stateCodecPrimitiveDecode()
    global.dropUpgrade = stateCodecPrimitiveDecode()
    global.eddieisdead = stateCodecPrimitiveDecode()
    global.elementsCollected = stateCodecPrimitiveDecode()
    global.enableCharge = stateCodecPrimitiveDecode()
    global.enableSlide = stateCodecPrimitiveDecode()
    global.endStageOnRoomEnd = stateCodecPrimitiveDecode()
    global.energyElements = stateCodecPrimitiveDecode()
    global.energySaver = stateCodecPrimitiveDecode()
    global.eTanks = stateCodecPrimitiveDecode()
    global.eventArgs = stateCodecPrimitiveDecode()
    global.execute_gml_function_ERR = stateCodecPrimitiveDecode()
    global.factionStance = stateCodecPrimitiveDecode()
    global.familyFriendlyText = stateCodecPrimitiveDecode()
    global.flag = stateCodecPrimitiveDecode()
    global.flagParent = stateCodecPrimitiveDecode()
    global.flashTimer = stateCodecPrimitiveDecode()
    global.font = stateCodecPrimitiveDecode()
    global.freeMovement = stateCodecPrimitiveDecode()
    global.frozen = stateCodecPrimitiveDecode()
    global.gameSpeed = stateCodecPrimitiveDecode()
    global.gameTimer = stateCodecPrimitiveDecode()
    global.gml_fn_retval = stateCodecPrimitiveDecode()
    global.gravityLiftBulletMap = stateCodecDSDecode(ds_type_map)
    global.gravityLiftLockJumpMap = stateCodecDSDecode(ds_type_map)
    global.gravityLiftLockMap = stateCodecDSDecode(ds_type_map)
    global.gravityLiftXSpeedMap = stateCodecDSDecode(ds_type_map)
    global.gunshot = stateCodecPrimitiveDecode()
    global.hasTeleported = stateCodecPrimitiveDecode()
    global.healthEffect = stateCodecPrimitiveDecode()
    global.infiniteEnergy = stateCodecPrimitiveDecode()
    global.inGame = stateCodecPrimitiveDecode()
    global.isInvincible = stateCodecPrimitiveDecode()
    global.jumpSound = stateCodecPrimitiveDecode()
    global.keyCoinCollected = stateCodecPrimitiveDecode()
    global.keyCoinTotal = stateCodecPrimitiveDecode()
    global.keyNumber = stateCodecPrimitiveDecode()
    global.lastTeleporterX = stateCodecPrimitiveDecode()
    global.lastTeleporterY = stateCodecPrimitiveDecode()
    global.levelLoop = stateCodecPrimitiveDecode()
    global.levelLoopEnd = stateCodecPrimitiveDecode()
    global.levelLoopStart = stateCodecPrimitiveDecode()
    global.levelReward = stateCodecPrimitiveDecode()
    global.levelRunInvalidReason = stateCodecPrimitiveDecode()
    global.levelRunValid = stateCodecPrimitiveDecode()
    global.levelSong = stateCodecPrimitiveDecode()
    global.levelSongType = stateCodecPrimitiveDecode()
    global.levelTrackNumber = stateCodecPrimitiveDecode()
    global.levelVolume = stateCodecPrimitiveDecode()
    global.leverPropagated = stateCodecPrimitiveDecode()
    global.livesEnabled = stateCodecPrimitiveDecode()
    global.livesRemaining = stateCodecPrimitiveDecode()
    global.lockBuster = stateCodecPrimitiveDecode()
    global.lockPoolAvailable = stateCodecPrimitiveDecode()
    global.lockPoolLockCount = stateCodecPrimitiveDecode()
    global.lockPoolLockTable = stateCodecPrimitiveDecode()
    global.lockPoolN = stateCodecPrimitiveDecode()
    global.lockPoolTombstone = stateCodecPrimitiveDecode()
    global.lockTransition = stateCodecPrimitiveDecode()
    global.maxBolts = stateCodecPrimitiveDecode()
    global.maxETanks = stateCodecPrimitiveDecode()
    global.maxLives = stateCodecPrimitiveDecode()
    global.maxMTanks = stateCodecPrimitiveDecode()
    global.maxPlayerCount = stateCodecPrimitiveDecode()
    global.maxWTanks = stateCodecPrimitiveDecode()
    global.MeBounce = stateCodecPrimitiveDecode()
    global.mmColor = stateCodecPrimitiveDecode()
    global.mTanks = stateCodecPrimitiveDecode()
    global.musicsound = stateCodecPrimitiveDecode()
    global.nextRoom = stateCodecPrimitiveDecode()
    global.outlineCol = stateCodecPrimitiveDecode()
    global.pickupGraphics = stateCodecPrimitiveDecode()
    global.playerCount = stateCodecPrimitiveDecode()
    global.playerCountInitialized = stateCodecPrimitiveDecode()
    global.playerFrozen = stateCodecPrimitiveDecode()
    global.playerHealth = stateCodecPrimitiveDecode()
    global.playerLock = stateCodecPrimitiveDecode()
    global.playerProjectileCreator = stateCodecPrimitiveDecode()
    global.playerSprite = stateCodecPrimitiveDecode()
    global.playerSpriteMax = stateCodecPrimitiveDecode()
    global.playingcustommusic = stateCodecPrimitiveDecode()
    global.previousRoom = stateCodecPrimitiveDecode()
    global.prevXView = stateCodecPrimitiveDecode()
    global.prevYView = stateCodecPrimitiveDecode()
    global.primaryCol = stateCodecPrimitiveDecode()
    global.quadHeight = stateCodecPrimitiveDecode()
    global.quadMarginBottom = stateCodecPrimitiveDecode()
    global.quadMarginTop = stateCodecPrimitiveDecode()
    global.quadWidth = stateCodecPrimitiveDecode()
    global.queuePaused = stateCodecPrimitiveDecode()
    global.respawnAllowed = stateCodecPrimitiveDecode()
    global.respawnAnimation = stateCodecPrimitiveDecode()
    global.respawnDonateThreshold = stateCodecPrimitiveDecode()
    global.respawnGravityAngle = stateCodecPrimitiveDecode()
    global.respawnTime = stateCodecPrimitiveDecode()
    global.respawnTimeBoss = stateCodecPrimitiveDecode()
    global.respawnTimer = stateCodecPrimitiveDecode()
    global.retval = stateCodecPrimitiveDecode()
    global.retval_error = stateCodecPrimitiveDecode()
    global.retval_exprlen = stateCodecPrimitiveDecode()
    global.retval_exprval = stateCodecPrimitiveDecode()
    global.roomReturn = stateCodecPrimitiveDecode()
    global.roomReturnIsHub = stateCodecPrimitiveDecode()
    global.roomReturnIsStage = stateCodecPrimitiveDecode()
    global.roomTimer = stateCodecPrimitiveDecode()
    global.secondaryCol = stateCodecPrimitiveDecode()
    global.sectionBottom = stateCodecPrimitiveDecode()
    global.sectionLeft = stateCodecPrimitiveDecode()
    global.sectionRight = stateCodecPrimitiveDecode()
    global.sectionTop = stateCodecPrimitiveDecode()
    global.shakeFactorX = stateCodecPrimitiveDecode()
    global.shakeFactorY = stateCodecPrimitiveDecode()
    global.shakeTimer = stateCodecPrimitiveDecode()
    global.sheepBlockStack = stateCodecPrimitiveDecode()
    global.sheepBlockStack_n = stateCodecPrimitiveDecode()
    global.shotUpgrade = stateCodecPrimitiveDecode()
    global.showMovingText = stateCodecPrimitiveDecode()
    global.skullAmulet = stateCodecPrimitiveDecode()
    global.songMemory = stateCodecPrimitiveDecode()
    global.soundvolume = stateCodecPrimitiveDecode()
    global.stageStartRoom = stateCodecPrimitiveDecode()
    global.sturdyHelmet = stateCodecPrimitiveDecode()
    global.superArmInterface = stateCodecPrimitiveDecode()
    global.switchingSections = stateCodecPrimitiveDecode()
    global.teleportSound = stateCodecPrimitiveDecode()
    global.teleportX = stateCodecPrimitiveDecode()
    global.teleportY = stateCodecPrimitiveDecode()
    global.telTelWeather = stateCodecPrimitiveDecode()
    global.tempSongData = stateCodecPrimitiveDecode()
    global.tileLayers = stateCodecPrimitiveDecode()
    global.tileLayersN = stateCodecPrimitiveDecode()
    global.timeStopped = stateCodecPrimitiveDecode()
    global.totalWeapons = stateCodecPrimitiveDecode()
    global.vsync = stateCodecPrimitiveDecode()
    global.waveManWarpLock = stateCodecPrimitiveDecode()
    global.weapon = stateCodecPrimitiveDecode()
    global.weaponHotbar = stateCodecPrimitiveDecode()
    global.weaponIcon = stateCodecPrimitiveDecode()
    global.weaponLocked = stateCodecPrimitiveDecode()
    global.weaponName = stateCodecPrimitiveDecode()
    global.weaponObject = stateCodecPrimitiveDecode()
    global.weaponPrimaryColor = stateCodecPrimitiveDecode()
    global.weaponSecondaryColor = stateCodecPrimitiveDecode()
    global.wTanks = stateCodecPrimitiveDecode()
    global.keyLeft = stateCodecPrimitiveDecode();
    global.keyRight = stateCodecPrimitiveDecode();
    global.keyUp = stateCodecPrimitiveDecode();
    global.keyDown = stateCodecPrimitiveDecode();
    global.keyJump = stateCodecPrimitiveDecode();
    global.keyShoot = stateCodecPrimitiveDecode();
    global.keySlide = stateCodecPrimitiveDecode();
    global.keyPause = stateCodecPrimitiveDecode();
    global.keyWeaponSwitchLeft = stateCodecPrimitiveDecode();
    global.keyWeaponSwitchRight = stateCodecPrimitiveDecode();
}
